[project]
name = "evepicalculator"
version = "1.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "ruff>=0.9.5",
]
